algoritmo "semnome"
// Função :
// Autor :
// Data : 22/8/2018
// Seção de Declarações 
var
    a, b, c, media: real
inicio
      Escreva("Escreva o primeiro número: ")
      leia (a)
      Escreva("Escreva o segundo número: ")
      leia (b)
      Escreva("Escreva o terceiro número: ")
      leia (c)
      media <- (a+b+c)/3
      Escreva("A media obtida entre os três números é: ", media)
      
fimalgoritmo
